# Generated by Django 2.0.4 on 2018-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('date', models.DateTimeField(db_column='date', max_length=100)),
                ('account', models.CharField(db_column='account', max_length=20, primary_key=True, serialize=False)),
                ('bet', models.IntegerField(db_column='bet', max_length=20)),
                ('number', models.CharField(db_column='number', max_length=20)),
                ('durationBet', models.IntegerField(db_column='durationBet', max_length=20)),
            ],
        ),
    ]
