# Generated by Django 2.0.4 on 2018-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='account',
            field=models.CharField(db_column='account', max_length=20, primary_key=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='date',
            field=models.DateTimeField(db_column='date', max_length=100, primary_key=True, serialize=False),
        ),
    ]
