# Generated by Django 2.0.4 on 2018-04-27 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20180423_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='authority',
            field=models.PositiveIntegerField(db_column='authority', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='login1',
            name='bet',
            field=models.IntegerField(db_column='bet'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='certified',
            field=models.CharField(db_column='certified', max_length=20),
        ),
        migrations.AlterField(
            model_name='login1',
            name='introBet',
            field=models.IntegerField(db_column='introBet'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='money',
            field=models.IntegerField(db_column='money'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='totalIntro',
            field=models.IntegerField(db_column='totalIntro'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='totalMoney',
            field=models.IntegerField(db_column='totalMoney'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='totalPer',
            field=models.IntegerField(db_column='totalPer'),
        ),
    ]
